easy_admin:
    entities:
        Attribute:
            class: gbenitez\Bundle\AttributeBundle\Entity\Attribute
            label: Form Attributes
            templates:
                new: "@Attribute/easy_admin/new.html.twig"
                edit: "@Attribute/easy_admin/edit.html.twig"
            list:
                title: 'Form Attributes'
                fields: ['id', 'name', 'presentation', 'type', 'targetEntity', 'active']
            form:
                fields:
                    - 'name'
                    - 'presentation'
                    -
                        property: 'targetEntity'
                        type: 'gbenitez\Bundle\AttributeBundle\Form\Type\Admin\TargetEntityType'
                    - { property: 'type' }
                    -
                        property: 'owner'
                        type: 'Entity'
                    -
                        property: 'region'
                        type: 'entity'
                        type_options:
                            class: gbenitez\Bundle\AttributeBundle\Entity\Region
                    -
                        property: 'configuration'
                        type: 'gbenitez\Bundle\AttributeBundle\Form\Type\YamlType'
                        type_options:
                            attr: { 'data-ace': 'yaml' }
                    -
                        property: constraints
                        type: 'gbenitez\Bundle\AttributeBundle\Form\Type\YamlType'
                        type_options:
                            attr: { 'data-ace': 'yaml' }
                    -
                        property: 'javascriptCode'
                        type: 'textarea'
                        type_options:
                            attr: { 'data-ace': 'javascript' }
                    - 'active'
        Region:
            class: gbenitez\Bundle\AttributeBundle\Entity\Region
            label: 'Regions [Attributes]'
